### ISSUE TITLE
handle incorrect time.Duration value

### ISSUE THREAD

**Issue by hellt** [karimra/gnmic#267]
if you pass `1y` value as a duration for the prometheus expiration value, the panic happens

```
gnmic 2021/01/06 13:23:45.954318 starting output type prometheus
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x5093c1]

goroutine 38 [running]:
log.(*Logger).Output(0x0, 0x2, 0xc0002ae900, 0x80, 0x0, 0x0)
	/usr/local/go/src/log/log.go:162 +0x81
log.(*Logger).Printf(0x0, 0x114ca1e, 0x2a, 0xc0004d1f78, 0x1, 0x1)
	/usr/local/go/src/log/log.go:188 +0x7e
github.com/karimra/gnmic/outputs/prometheus_output.(*PrometheusOutput).Init(0xc0003cbd50, 0x12d6360, 0xc000379e80, 0xc0003b2f00, 0xc00047d780, 0x2, 0x2, 0xc00047e340, 0xc000317980)
	/root/gnmic/outputs/prometheus_output/prometheus_output.go:124 +0x7af
created by github.com/karimra/gnmic/collector.(*Collector).InitOutput
	/root/gnmic/collector/collector.go:217 +0x38e
```

**Comment by hellt** [comment]
confirmed
```
prometheus_output 2021/01/07 14:00:46.426714 prometheus output config decode failed: 1 error(s) decoding:

* error decoding 'expiration': time: unknown unit y in duration 1y
```
