### ISSUE TITLE
HTTP Loader help

### ISSUE THREAD

**Issue by VahidTa** [karimra/gnmic#576]
Hi,

Is there any http body template to help for API body format?

I am getting this error:

```
[http_loader] result: map[targets:{"name":"router1","address":"192.168.1.1:57400"}]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x48795e]

 goroutine 16 [running]:
sync.(*RWMutex).Lock(0xc0008761e0)
      /opt/hostedtoolcache/go/1.17.2/x64/src/sync/rwmutex.go:111 +0x1e
github.com/karimra/gnmic/loaders/http_loader.(*httpLoader).updateTargets(0xc0001da280, {0x27354a8, 0xc000535b00}, 0x27354a8, 0x9502f900)
      /home/runner/work/gnmic/gnmic/loaders/http_loader/http_loader.go:299 +0x206
github.com/karimra/gnmic/loaders/http_loader.(*httpLoader).update(0xc0001da280, {0x27354a8, 0xc000535b00}, 0xc000905fb8)
      /home/runner/work/gnmic/gnmic/loaders/http_loader/http_loader.go:188 +0xcc
github.com/karimra/gnmic/loaders/http_loader.(*httpLoader).Start.func1()
     /home/runner/work/gnmic/gnmic/loaders/http_loader/http_loader.go:153 +0xde
created by github.com/karimra/gnmic/loaders/http_loader.(*httpLoader).Start
      /home/runner/work/gnmic/gnmic/loaders/http_loader/http_loader.go:149 +0xfa
```

**Comment by karimra** [comment]
Hi @VahidTa 

If you don't plan to use any GoTemplate to transform the response body, it should look like this:
```json
{
    "router1": {
        "address": "<ip>",
        "username": "admin"
         // other fields
    },
    "router2": {
        "address": "<ip>",
        "username": "admin"
        // other fields
    }
}
```
The fields under each target are the same as the ones you would put in the config file.
Note that only "address" is required, the other fields can be set from the configuration file main section.

Also, please use the latest release v0.24.4, there was an uninitialized variable in the the http_loader that led to the nil pointer dereference you showed ( thanks for that )
